mapbox/geojson.io

- dist/site.js
- dist/site.mobile.js
- src/source/gist.js
Adds a missing '/' in the URL used to fetch a gist.
For example, here's the link in API.md which is currently broken:
http://geojson.io/#id=gist:tmcw/e9a29ad54dbaa83dee08&map=8/39.198/-76.981
Previously was trying to fetch URLs like: https://api.github.com/gistsabcde - which would 404.
Proper URL is like: https://api.github.com/gists/abcde
> Fixes gist URL API

- README.md
I changed this link to point to the GitHub repo because I shut down the GitSpatial server a month or so ago. Feel free to just remove the link entirely if you want, since the app has been shut down :smile:.
> Change GitSpatial link to GitHub repo, not the no-longer-running app.

- css/marker.css
- css/site.css
- data/maki.json
- dist/site.js
- dist/site.mobile.js
- src/ui/map.js
Provide HTML5 inputs to help users style features. Uses color type for marker-color, stroke & fill, number type for stroke-width, range slider for stroke-opacity & fill-opacity, and datalist for marker-size & marker-symbol. Falls back to text input for unsupported browsers.
Additional area and length measurements and metadata moved to Info tab to maximize space.
> Tabbed popups and style inputs

- .travis.yml
Since the tests for geojson.io do not need `sudo` during tests, we should add the `sudo: false` parameter to the travis.yml file. This will speed up test times on travis. 
ref: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
> add sudo false for faster travis builds

- dist/site.js
- dist/site.mobile.js
- src/ui/file_bar.js
1. Anonymous gisting was erroring for offline users, so it's now disabled by default when API Endpoint is configured for Atlas Server.
2. `New` button now opens a new window with a relative url instead of `/#new` at root.
cc @tmcw
> Offline error cleanup

- src/ui/layer_switch.js
OpenCycleMap is a very popular OSM tileset. We would find this a very useful background to have available.
> Add OpenCycleMap option to layer switcher

- dist/site.js
- dist/site.mobile.js
- src/panel/json.js
This fixes a bug where, if you have scrolled down the JSON panel, made an edit, then added added a new feature on the map, the JSON panel would scroll back to the top instead of maintaining its position
> Maintain editor scroll position after map change

- dist/site.js
- dist/site.mobile.js
- src/ui/map.js
The attribution is currently covering the basemap buttons on smaller screens. This frees up some room, allowing for more basemaps and attribution/info.
> Swap attributionControl for infoControl

- API.md
Changes broken link in API.md to the one used in Github's geojson doc (old: tmcw ... new: benbalter): https://help.github.com/articles/mapping-geojson-files-on-github/ . This same broken link exists in the help tab (and this same correction would fix issue #434). I haven't tracked down how geojson.io constructs that help tab though, so getting that all squared away is another matter.
> correct broken link in the API.md

- dist/site.js
- dist/site.mobile.js
- src/ui/map.js
re: #469 
Recent changes to the API token used in geojson.io makes using `mapbox.places-permanent` untenable.
> mapbox.places-permanent -> mapbox.places

- index.html
Need to explicitly add `data:` to the content security policy to avoid warnings on `data:` urls
`*` does not catch these, because it's treated as a source, not a protocol
see also http://stackoverflow.com/a/18449556/7620
relates to #499
> Eliminate CSP warning for data: scheme

- data/share.html
- package.json
* Bumps gist-map-browser
* Uses the DOM to create tables for markers on `data/share.html`
/cc @tmcw
> Use the DOM to create tables for markers

- src/ui/map.js
The feedback link on geojson.io reports to my inbox, and I no longer maintain / have commit access / provide support for geojson.io.
Feel free to replace it with a link to a Mapbox-operated feedback mechanism, or anything else, but it's unfortunate for it to be essentially `/dev/null` right now.
> Remove feedback link

- package.json
Node 7 was the current version at the time package.json was last modified and users report in #639 that the app doesn't install with 8+.
> Requires Node versions < 8

- dist/site.js
- dist/site.mobile.js
- src/ui/layer_switch.js
Adds a style with a single raster source and layer to `layer_switch.js` to bring the OSM tileset back as a basemap option
> add osm raster tiles as a base layer option

- unsupported.html
When I go to geojson.io, the message say my browser is out of date, which is weird given I run Firefox 105.0.2, and while 106.0 is out since 3 days, the real issue is that I disabled WebGL a long time ago. So I propose to change the error message to give a clue in case someone did like me (either disabled due to issue with driver stability, or disabled to avoid fingerprinting as it was done on some version of the tor browser)
> Add better error message when WebGL is not enabled

- dist/site.js
- dist/site.mobile.js
- src/core/loader.js
- src/ui/map/index.js
Updates the function that checks whether the map has moved from its default position which previously depended on Leaflet.
To test, load the local server with `#id=github:ebrelsford/geojson-examples/blob/master/brooklyn.geojson` appended to the URL.
Note: There is still a race condition that may prevent the markers from showing up in the above example, this is logged in #728 
This PR will get rid of the Leaflet error, but the map data may not display until we address the race condition.
Fixes #724
> update default view, fix mapDefault() check

- dist/site.js
- dist/site.mobile.js
- src/lib/meta.js
- src/ui/file_bar.js
- src/ui/layer_switch.js
- src/ui/map/index.js
Restores "Add Map Layer" option in the Meta menu
- Menu text changed to "Add raster tile layer"
- Adding the raster layer sets the map style to a new style with only the raster layer and the geojson data/draw layers
- Adding the raster layer appends a button to the style selection UI
- User can switch between the custom style and the core styles until reload
- If user adds another raster layer when one has already been added, it will overwrite the existing one
> restore add raster layer functionality

- .vscode/settings.json
- Makefile
- README.md
Improves the hot reloading configuration.
- `Run on save` only watches the directories and files that are processed by `make`, runs `make` when any of them change.
- `Live Server` ignores the same directories and files, but hot reloads on all others.
- Adds a `wait` setting to `Live Server` which prevents multiple sequential reloads as `make` saves multiple files simultaneously.
- Updates the readme with more info on this setup
> improve hot reload setup

- CHANGELOG.md
- dist/site.js
- dist/site.mobile.js
- src/ui/map/util.js
Closes #728 
`geojsonToLayer()` is fired when `context.data` changes, triggering a `map.setData()` and re-rendering of markers. 
It was checking for `map.isStyleLoaded()` which was returning false and preventing the initial setData() from  running.
> check for source instead of isStyleLoaded()

- CHANGELOG.md
- dist/site.js
- dist/site.mobile.js
- src/ui/map/index.js
Prevents two popups from appearing when a marker located within a polygon is clicked.
Closes #710
Also adds `drawing` state boolean to prevent popup from showing when a drawn feature's last vertex is within an existing geometry.  (simple example: draw a new point feature within an existing polygon, the polygon's popup will open)
> prevent line or polygon popup if marker was clicked

- dist/site.js
- dist/site.mobile.js
- package-lock.json
- package.json
- src/panel/json.js
The JSON editor is both responding to changes when `context.data` is updated, and updating `context.data` when changes are detected in the editor.  This creates circular logic where the editor tries to set `context.data` to the same value it just received.
1) editor detects change in `context.data`, sets editor value
2) editor picks up this change as an edit, sets `context.data`
3) editor detects change in `context.data` but knows it was initiated by the editor so it ignores it.
Once data is loaded from a URL parameter or file, the same sequence repeats.
This PR interrupts #2 above and will only set `context.data` if the current value in the text editor is different (meaning the user has edited the geojson) 
The bigger reason to fix this inefficiency is because each time `context.data` is …
> prevent editor data update when data is unchanged

- dist/site.js
- dist/site.mobile.js
- src/constants.js
- src/ui/layer_switch.js
- src/ui/map/index.js
- src/ui/map/styles.js
- src/ui/projection_switch.js
- Adds `projection` and `style` to localstorage, so the user's selections for both options will persist between reloads.
- Adds `constants.js` with defaults for both values which are used in more than one place (both the UI and map init need to check for the existence of these values in localstorage or use the default)
Closes #719
> Persist projection and style

- dist/site.js
- dist/site.mobile.js
- src/core/data.js
- src/lib/meta.js
- src/ui/file_bar.js
- src/ui/layer_switch.js
- src/ui/map/index.js
Instead of listening for `style.load`, which is not part of the public api, we add `mapStyleLoaded` as a boolean to `context.data`.  When the user clicks a different style, `mapStyleLoaded` is set to `true`.  On the map `idle` event, if `mapStyleLoaded` is true and the map does not already contain the working dataset sources and layers, we add them and set `mapStyleLoaded` to false.  
This method also works when toggling between a user-added raster layer and any of the existing base styles (fixing #740)
> fix style load check

- css/site.css
Fixes a misalignment of the sidebar tabs caused by the widened codemirror gutter. <img width="408" alt="geojson_io" src="https://user-images.githubusercontent.com/1833820/198862322-06dc1b18-108f-447b-a150-46d07938a426.png">
Bumps the mapboxgl top right controls down when in fullscreen mode so there is no overlap with the sidebar header.
> fix sidebar tab alignment, fix gl control margin in fullscreen mode

- css/site.css
- dist/site.js
- dist/site.mobile.js
- src/panel/json.js
- src/ui/map/index.js
Adds keybindings:
- When editing `delete` will trigger `draw.trash()`, removing a selected feature or vertex
- When not editing, 
- - `m` will change the draw mode to `draw_point`
- - `l` will change the draw mode to `draw_line_string`
- - `p` will change the draw mode to `draw_polygon`
- - `r` will change the draw mode to `draw_rectangle`
- - `c` will change the draw mode to `draw_rectangle`
Also fixes site.css where some merge conflict markers were accidentally committed.
> add keybindings for draw mode changes and trash

- css/marker.css
- dist/site.js
- dist/site.mobile.js
- src/lib/popup.js
- src/ui/map/util.js
Handles the `marker-size` simplestyle-spec property.   (this was not included in #718 for some reason) `marker-icon` is the only remaining unsupported simplestyle property.
Restores simplestyle property creation/editing in the popup UI (Closes #756) with the following changes:
- Instead of a checkbox, there is a text button `Add Simplestyle Properties`.  When clicked, it appends the style properties for the current feature type to the properties table.  These will not take effect until the user clicks the save button.   (the previous implementation always included the style rows, but hid the rows, so they would be added on save whether the user wanted them or not. #498)
- Adds some logic to determine whether to show the `Add Simplestyle Properties` button (do not show it if all of the …
> restore simplestyle ui in popups, handle marker-size style property

- dist/site.js
- src/ui/map/util.js
Tiny bugfix for handling MultiPoint rendering when properties is `null`. 
Diccovered when testing a MultiPoint URL from #661 
[Test URL ](http://geojson.io/#data=data:application/json,%7B%22type%22%3A%22MultiPoint%22%2C%22coordinates%22%3A%5B%5B-122.3858692%2C47.56452925%5D%2C%5B-122.387177%2C47.561455%5D%2C%5B-122.38679%2C47.562161%5D%2C%5B-122.386375%2C47.568764%5D%2C%5B-122.41095%2C47.577553%5D%2C%5B-122.3870841%2C47.5614664%5D%2C%5B-122.407364%2C47.577271%5D%2C%5B-122.386637%2C47.579173%5D%2C%5B-122.385849%2C47.562884%5D%2C%5B-122.4109498%2C47.5775947%5D%2C%5B-122.3869421%2C47.5819689%5D%2C%5B-122.40967%2C47.57968%5D%2C%5B-122.386024%2C47.583717%5D%2C%5B-122.386383%2C47.56538%5D%2C%5B-122.3847046%2C47.5826992%5D%5D%7D)
> handle null properties when rendering MultiPoint

- css/site.css
- dist/site.js
- src/lib/validate.js
Status Quo:
geojson in the code editor is validated using `geojsonhint` which returns an array of error objects.  If this array is not empty, the geojson is considered invalid and is not rendered/updated, and the errors are highlighted in red in the codemirror gutter.
In this PR:
- Checks the array returned from geojsonhint for objects that do not contain a `level` property.  These are "rejectable" errors and if any of these exist, reject the geojson and highlight the errors in the same way as the status quo.
- When geojson does not yield any rejectable errors from geojsonhint, accept it, but also highlight any warnings in yellow.
Example: Feature missing `properties` key yields an error, polygon that does not follow the right-hand-rule yields a warning.
Closes #784
> show geojsonhint warnings without rejecting geojson

- data/help.html
- dist/site.js
- src/panel/json.js
- src/ui/map/util.js
- Adds a normalization step to the validation of data from the code editor.  This ensures that the the working dataset is **always** a FeatureCollection.  Prior to this PR, data imported via the 'Open' menu button or by drag and drop is normalized into a FeatureCollection, but data loaded via pasting geojson into the code editor or by loading from a url or gist is not.  
- Refactors the code for rendering markers to always expect a FeatureCollection.  
- Updates `help` to include a statement about the working dataset always being a FeatureCollection
- Minor change to the description of what geojson.io is, to match the description in the github repo
Examples of inconsistencies prior to this PR:
- If the user pastes/loads a Feature or Geometry, it will appear on the map but there will be …
> normalize pasted data into FeatureCollection

- dist/site.js
- src/ui/map/index.js
- src/ui/map/styles.js
Core styles updates launched today!
https://www.mapbox.com/blog/mapbox-core-styles-redesigns
Edit:  Since some of the core styles include fog, we drop the `setFog()` that happens on each style change.  Instead we use the style's fog settings  for Streets, Satellite-Streets, and Outdoors.  For the other styles we manually set the fog.
> update core style urls

- data/help.html
- src/ui/draw/direct_select.js
- src/ui/draw/simple_select.js
- src/ui/map/index.js
Closes https://github.com/mapbox/geojson.io/issues/780 by making it more difficult to move entire features.
Requires Shift + drag to move one or more selected features.
Documents this in help.html along with some other editing tips
> require shift key to drag features, update help text

- package-lock.json
- package.json
- rollup.config.js
In troubleshooting #804 I discovered that the minified js bundle (minified by `rollup-plugin-terser`) was causing an error when using `Flatten Multi Features`.  For some reason, the value pulled from `context.data.get('map')` was being mutated immediately after the button is clicked and the action is called.  The `features` array changed to `undefined` and yielded errors with downstream functions that were expecting an array.
This behavior did not occur in development, so it's a direct result of the terser minification.
Rather than go down the rabbithole of figuring out a mysterious mutation, I tried other minification options for rollup and landed on `rollup-plugin-uglify` which seems to solve the problem.
Closes #804
> replace terser with uglify

- README.md
- src/lib/zoomextent.js
Before, opening a file from the default globe view takes about 5s to zoom in. This feels excessive to me:
https://user-images.githubusercontent.com/1664407/212032226-3ae3b2cd-6780-447d-a586-76278d5b3d1b.mp4
I've capped it in this PR to 1s:
https://user-images.githubusercontent.com/1664407/212032290-15acf646-1850-4e7d-8606-e0a2424019a3.mp4
This feels much more convenient to me, but it is an opinionated design question, so happy for other ideas. Also, the change affects other uses of `zoomextent`, like clicking "Zoom to features", loading WKB text, etc.
> Speed up the flying animations

- API.md
Updates the example link for the `data=data:text/x-url` url parameter.  The old link was from a legacy mapbox api call that now returns an error message instead of geojson.
The new example uses a geojson file hosted on github for counties in the U.S. state of California.
> update external geojson example link

- API.md
- src/core/api.js
- src/index.js
- src/ui/map/index.js
Restores the geojson.io `console api` with `map`, `draw`, and `data` properties available on `window.api`.  `API.md` is also restored to include documentation for the console api, with updated links (and references to leaflet and leaflet draw replaced with mapboxgl and mapbox-gl-draw)
Closes #806
> restore console api, update API.md to document it

- src/ui/map/util.js
Fixes #816 by fetching the full feature from the datastore before doing geometry calculations.  (use the feature returned by queryRenderedFeatures() only for getting the feature id, fetch the full feature by its id, then perform calculations.
> calculate geometry info based on the full feature

- src/ui/map/util.js
Fixes a regression introduced in #819 which broke buttons and within the popups.  Features are given an `id` property after being added to the map based on its position in the FeatureCollection, but this property may not exist on the data in the datastore.
#819 gets the `id` from `queryRenderedFeatures`, then uses it to look up the full feature from the datastore (by its index).   However, the retrieved feature does not include an `id` itself, so the "save" and "add simplestyle properties" buttons do not know which feature to update and an error is thrown.
Fixes #823 and #824
> fix popup buttons

- index.html
- package-lock.json
- package.json
- src/ui/map/index.js
Adds `mapbox-gl-rtl-text` plugin so that RTL labels (e.g. street names in Arabic) will display properly.
Adds an explicit mapbox-gl version to package.json
> add rtl text plugin

- package-lock.json
- package.json
- src/ui/draw/circle.js
Fixes #827.  The circle draw tool is an extension of the built-in linestring draw tool.  Some code was not copied over in the `onStop` method, which resulted in an endless loop.
- Updates `mapbox-gl-draw` to the latest, v1.4.1
> fix circle draw bug, upgrade mapbox-gl-draw

- index.html
Adds a script tag for the new Google Analytics 4 tracking.  Leaves the old GA tracking script in place, which we can remove once the service is retired.
> add ga4 tracking

- src/ui/map/styles.js
Fixes #812 
When using text-field for symbold in mapbox-gl-js, glyphs is required.
https://github.com/mapbox/mapbox-gl-js/blob/ec307c74bfe46f02e2b6f7292332caa5779a3f2e/src/style-spec/validate/validate_property.js#L54
> Fixed a bug when editing geometry in OSM style

- src/lib/zoomextent.js
- src/ui/map/util.js
Fixes #713 
Features that do not include geometry are not displayed on the map as markers and can be imported.
The geojson will be displayed in the right panel, same as when you copy and paste.
> Fix import bug when missing geometry

- src/ui/map/util.js
Small fix to check for the existence of properties before checking for `marker-symbol` property in `util.js`
Fixes #851
> fix check for marker-symbol property

- package-lock.json
- package.json
Updates geojsonhint to v3.2.0 which ignores a top-level crs property.  Closes #849
> bump geojsonhint to 3.2.0

- src/ui/map/index.js
Handles the case where `Streets` is kept in localstorage as the active style, causing a blank map because Streets has been replaced with Mapbox Standard.
> handle streets style in storage

- src/ui/map/index.js
Fixes a previous fix to handle `Streets` being stored in localstorage as the active style.
> fix streets storage handling

- CODEOWNERS
Adds the codeowners file to declare the docs team as owners of this repository
> Adding CodeOwners file

- package-lock.json
- package.json
Hi! Thank you for great application. When I run `npm install`, I got the error below. So, I solve the problem by update `@mapbox/mapbox-gl-geocoder@5.0.1` to `@5.0.2`
Colud you review it When you have time?
```
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @mapbox/mapbox-gl-geocoder@5.0.1
npm ERR! Found: mapbox-gl@3.1.2
npm ERR! node_modules/mapbox-gl
npm ERR!   mapbox-gl@"3.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer mapbox-gl@">= 0.47.0 < 3.0.0" from @mapbox/mapbox-gl-geocoder@5.0.1
npm ERR! node_modules/@mapbox/mapbox-gl-geocoder
npm ERR!   @mapbox/mapbox-gl-geocoder@"^5.0.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: mapbox-gl@2.15.0
npm ERR! …
```
> Fix dependency error

- API.md
- README.md
- data/help.md
- src/ui/file_bar.js
This PR fixes all instances in Markdown files where there was a reference to `http://`.  All public facing notes (API.md, help.md) now have `https://` as their protocol.
> Fix protocol in Markdown docs to be `https://`

- src/ui/file_bar.js
The API notes states that a URL of GeoJSON data can be encoded to open directly in <https://geojson.io>.  This PR adds that functionality to the user interface: 
* Update the User Interface > Meta > 🪟 New Window with GeoJSON URL
---
source: [API.md](https://github.com/mapbox/geojson.io/blob/main/API.md#datadataapplicationjson)
> "*Open the map and load a chunk of GeoJSON data from a URL segment directly onto the map. The GeoJSON data should be encoded as per encodeURIComponent(JSON.stringify(geojson_data)).*"
---
Open a Weather Forecast from Yosemite National Park
Open the live demo of this UI update:
* <https://roblabs.com/geojson>
* https://api.weather.gov/gridpoints/HNX/67,143/forecast
---
Putting it all together:
* <https://roblabs.com/geojson/#data=data:text/x-url,https%3A%2F%2Fapi.we …
> UI:  New Window with GeoJSON URL

- src/ui/file_bar.js
Hey, thanks for the great tool.
I have the use case that I often need to open multiple files at once. At the moment I need to use the open dialog multiple times to achieve this. With this change I can select multiple files in the dialog which are then opened.
* add multiple attribute to input tag
* iterate over selected files using existing file read behavior
Tested on Ubuntu 24.04 in Firefox and Chromium with up to 10 geojson files and it worked without any problem.
> open multiple files at once

- index.html
This PR adds GA4 tracking to geojson.io. This will help us analyze the useage in this tool outside of segment/mode reports (which dont offer the same level of data).
> Added g4a tracking
