- dist/site.js
- dist/site.mobile.js
- src/core/data.js
- src/core/repo.js
- src/source/gist.js
- src/source/github.js
- src/ui/file_bar.js
Couple of fixes post-github refactor.
Fixes #397 & #396
> Github + gist save fixes

- css/marker.css
- dist/site.js
- dist/site.mobile.js
- src/ui/map.js
This allows any additional features loaded via the API to have standard
popup styling.
> Use custom popup class for geojsonio features

- dist/site.js
- dist/site.mobile.js
- src/ui/map.js
> Style support for multi geometries

- dist/site.js
- dist/site.mobile.js
> Add dist missing from API.md change

- src/core/user.js
I had some trouble with authentication
if the hash tag is still in the address bar
> Fix get param for oauth process

- dist/site.js
- dist/site.mobile.js
- src/ui/map.js
Closes #482 and #489 
Disables the infoControl. The previous pieces of info (Feedback
and About) are now set as the prefix in the attribution control.
P.S. I'm never quite sure if I'm handling site.js and site.mobile.js properly. After `npm install` and `make` it seems to write a completely different file despite only changing a few lines.
> Use attribution control

- data/share.html
Updating embed HTML to use Mapbox FeatureLayer to support icon styling.
> Fix for #485 - Updating embed HTML to use L.mapbox.featureLayer

- src/ui/map.js
> Eliminating [object Object] from popup

- dist/site.js
- dist/site.mobile.js
- package.json
- src/ui/map.js
to comply with https://tools.ietf.org/html/rfc7946#section-3.1.6
> make sure generated polygons follow right-hand-rule

- data/share.html
> rotate access token

- data/share.html
> Revert "rotate access token"

- data/share.html
> Revert "Revert "rotate access token""

- dist/site.js
- dist/site.mobile.js
- package.json
- src/lib/meta.js
- src/ui/file_bar.js
Adds a new meta menu to load google-encoded-polyline encoded content. Fixes #554
> Load encoded polylines

- README.md
- package.json
- src/lib/meta.js
- src/ui/file_bar.js
This small change adds three menu items to the Meta menu, allowing the import and conversion of WKT strings, hex encoded WKB strings, and base64 encoded WKB strings.  It cleanly adds the basic features requested by issue #232, without dealing with file format issues.
The added libraries, WKX and Buffer, are both MIT licensed
> WKX (WKT/WKB) support

- CHANGELOG.md
- src/ui/layer_switch.js
OCM is no longer free for all. I propose to disable the layer, leaving instructions on how to enable it.
Resolves #577
> Disable OCM layer

- data/share.html
- dist/delegate.js
- dist/site.js
- dist/site.mobile.js
- src/ui/layer_switch.js
referencing new styles via `L.tilelayer` with url template because Mapbox.js 2.2.2 does not support `L.mapbox.styleLayer`, and attempt at updating led to further complications
> update from Studio Classic styles ahead of deprecation

- dist/site.js
- dist/site.mobile.js
- src/ui/layer_switch.js
The map's max zoom went level went to 18 after #664. This PR sets the maxZoom for layers to 22, thereby increasing the map's max zoom level to 22.
> Increase max zoom from 18 to 22

- README.md
- dist/site.js
- dist/site.mobile.js
- src/ui/map/index.js
- src/ui/map/util.js
Should resolve #721 
@chriswhong Lemme know what you think here; it feels dangerous to set a parameter to a default like this, but I couldn't find another way to do it.
> Pass writeable down to addMarkers

- dist/site.js
- dist/site.mobile.js
- src/ui/file_bar.js
> remove cmd-s keybinding

- src/ui/map/util.js
Fixes #768 
Added popup offsets to the Marker to account for all 8 anchor points.
> Fixes #768 by adding marker popup offsets

- index.html
Fixes double quotes that were pasted in incorrectly in #834
> add ga4 tracking

- package.json
Updates the npm lint command in package.json to check all js files.  Also updates the `format` and `lint-staged` commands
> update lint command

- README.md
- package-lock.json
- package.json
- src/lib/popup.js
- Fix ESLint error
- Remove Node.js engine mention in manifest
> Update GL JS to v3.5.2

- src/index.js
Update the site analytics write key
> update segment tracking
